# config.yaml

# ---------- DATA CONFIG ----------
start_year: 2015
end_year: 2025
league: EPL
raw_match_data_path: data/raw/match_data.csv
raw_elo_data_path: data/raw/elo_ratings.csv
raw_squad_data_path: data/raw/squad_data.csv
raw_fixtures_path: data/raw/2025_fixture_list.csv

# ---------- FEATURE ENGINEERING ----------
merged_trainset_path: data/input/merged_trainset.csv
final_trainset_path: data/input/clean_trainset.csv

# ---------- MODEL ----------
features_path: models/feature_cols.json
label_encoder_path: models/label_encoder.pkl
model_path: models/xgb_model.pkl

# ---------- PREDICTION ----------
gw_to_predict: 3
season_to_predict: 2025
threshold_ev: 0.05
output_predictions_path: data/output/predictions/{season_to_predict}_gw{gw_to_predict}.csv